# References:
# - https://starship.rs/presets/nerd-font

"$schema" = 'https://starship.rs/config-schema.json'

[aws]
symbol = 'ó°¸ '

[buf]
symbol = "ï’ "

[bun]
symbol = "î¯ "

[c]
symbol = 'î™‰ '

[cpp]
symbol = "î˜ "

[cmake]
symbol = "î” "

[conda]
symbol = "ï„Œ "

[crystal]
format = 'î˜¯ '

[dart]
format = 'î™Œ '

[deno]
symbol = "îŸ€ "

[directory]
read_only = " ó°Œ¾"

[direnv]
disabled = false

[docker_context]
detect_files = [
  'compose.yml',
  'compose.yaml',
  'docker-compose.yml',
  'docker-compose.yaml',
  'Containerfile',
  'Dockerfile',
]
symbol = "ïŒˆ "

[dotnet]
symbol = 'ó°ª® '

[elixir]
symbol = 'î˜­ '

[elm]
symbol = 'î˜¬ '

[erlang]
symbol = 'î± '

[fennel]
symbol = 'îš¯ '

[fossil_branch]
symbol = "ï˜ "

[gcloud]
format = 'on [$symbol$project]($style) '
symbol = 'ó±‡¶ '

[git_branch]
symbol = "ï˜ "

[git_commit]
tag_symbol = ' ï’ '

[golang]
symbol = 'î™ '

[guix_shell]
symbol = 'ïŒ¥ '

[gradle]
symbol = 'î™  '

[haskell]
symbol = 'î˜Ÿ '

[haxe]
symbol = 'î™¦ '

[hg_branch]
symbol = "ï˜ "

[hostname]
ssh_symbol = "î¬ "

[java]
symbol = 'îœ¸ '

[julia]
symbol = 'î˜¤ '

[kotlin]
symbol = 'î˜´ '

[kubernetes]
symbol = 'ó±ƒ¾ '

[lua]
symbol = 'î˜  '

[memory_usage]
symbol = "ó°› "

[nim]
symbol = 'î™· '

[nix_shell]
symbol = 'ó±„… '

[nodejs]
symbol = 'ó°™ '

[ocaml]
symbol = 'î™º '

[os.symbols]
Alpaquita = "îª¢ "
Alpine = 'ïŒ€ '
AlmaLinux = "ïŒ "
Amazon = 'ï‰° '
Android = 'ó°€² '
Arch = 'ó°£‡ '
Artix = 'ïŒŸ '
CachyOS = "ïŒƒ "
CentOS = 'ïŒ„ '
Debian = 'ïŒ† '
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = 'ïŒ¢ '
Fedora = 'ïŒŠ '
FreeBSD = 'ïŒŒ '
Garuda = 'ïŒ· '
Gentoo = 'ó°£¨ '
HardenedBSD = "ó°Œ "
Illumos = 'ïŒ¦ '
Kali = "ïŒ§ "
Linux = 'ó°Œ½ '
Mabox = "î¬© "
Macos = 'îœ‘ '
Manjaro = 'ïŒ’ '
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = 'ó°£­ '
NetBSD = "ğŸš© "
NixOS = "ïŒ“ "
Nobara = "ï€ "
OpenBSD = 'ïŒ¨ '
openSUSE = 'ïŒ” '
OracleLinux = "ó°Œ· "
Pop = 'ïŒª '
Raspbian = "ïŒ• "
Redhat = 'ó±„› '
RedHatEnterprise = 'ó±„› '
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = 'ïŒ­ '
SUSE = "ïŒ” "
Ubuntu = 'îœº '
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "

[package]
symbol = "ó°— "

[perl]
symbol = 'î™¾ '

[php]
symbol = 'îœ½ '

[pijul_channel]
symbol = "ï˜ "

[pixi]
symbol = "ó°— "

[purescript]
symbol = 'î˜° '

[python]
symbol = 'î˜† '

[rlang]
symbol = 'îšŠ '

[ruby]
symbol = 'î˜… '

[rust]
symbol = 'îš‹ '

[scala]
symbol = 'îš '

[swift]
symbol = 'îš™ '

[terraform]
format = 'via [$symbol$version]($style) '
symbol = 'îšš '
detect_extensions = ['tf', 'tfplan', 'tfstate', 'tfvars']
detect_files = ['terragrunt.hcl']

[vlang]
symbol = 'îš¬ '

[zig]
symbol = 'îš© '
