"$schema" = "https://starship.rs/config-schema.json"
command_timeout = 5000

[aws]
symbol = " "

[azure]
symbol = " "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[cobol]
symbol = "󰒓 "

[conda]
symbol = " "

[crystal]
format = " "

[dart]
format = " "

[deno]
symbol = " "

[directory]
read_only = " 󰌾"

[direnv]
disabled = false

[docker_context]
detect_files = [
  "compose.yml",
  "compose.yaml",
  "docker-compose.yml",
  "docker-compose.yaml",
  "Containerfile",
  "Dockerfile",
]
symbol = " "

[dotnet]
format = "via [$symbol($version )(󰣉 $tfm )]($style)"
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[erlang]
symbol = " "

[fennel]
symbol = " "

[fortran]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]  #
format = "on [$symbol$project]($style) "
symbol = " "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = "  "

[gleam]
symbol = "󰓎 "

[golang]  #
symbol = " "

[guix_shell]
symbol = " "

[gradle]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[helm]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[kubernetes]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[mise]
disabled = false

[mojo]
symbol = "󰈸  "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[opa]
symbol = " "

[openstack]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
Bluefin = ""
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = " "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = " "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = "󰣭 "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = " "
OpenCloudOS = "󰅟 "
openEuler = "󰏒 "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = " "
SUSE = " "
Ubuntu = " "
Ultramarine = " "
Unknown = " "
Uos = " "
Void = " "
Windows = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[pulumi]
symbol = " "

[purescript]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = " "

[raku]
symbol = " "

[red]
symbol = "󰔶 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = "󰹹 "

[solidity]
symbol = " "

[spack]
symbol = " "

[status]
symbol = ""
not_executable_symbol = ""
not_found_symbol = "󰍉"
sigint_symbol = "󱊈"

[sudo]
symbol = "󱑷 "

[swift]
symbol = " "

[terraform]
format = "via [$symbol$version]($style) "
symbol = " "
detect_extensions = ["tf", "tfplan", "tfstate", "tfvars"]
detect_files = ["terragrunt.hcl"]

[typst]
symbol = " "

[vagrant]
symbol = " "

[xmake]
symbol = " "

[zig]
symbol = " "
