# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[aws]
symbol = 'ó°¸ '

[c]
symbol = 'î™‰ '

[crystal]
format = 'î˜¯ '

[dart]
format = 'î™Œ '

[direnv]
disabled = true # @TODO

[docker_context]
detect_files = [
  'compose.yml',
  'compose.yaml',
  'docker-compose.yml',
  'docker-compose.yaml',
  'Dockerfile',
]

[dotnet]
symbol = 'ó°ª® '

[elixir]
symbol = 'î˜­ '

[elm]
symbol = 'î˜¬ '

[erlang]
symbol = 'î± '

[fennel]
symbol = 'îš¯ '

[gcloud]
format = 'on [$symbol$project]($style) '
symbol = 'ó±‡¶ '
[gcloud.project_aliases]
solarmonkey-app = 'prod'
solar-monkey-internal-tools = 'tools'
solarmonkey-non-production = 'nonprod'

[golang]
symbol = 'î™ '

[guix_shell]
symbol = 'ïŒ¥ '

[gradle]
symbol = 'î™  '

[haskell]
symbol = 'î˜Ÿ '

[haxe]
symbol = 'î™¦ '

[java]
symbol = 'îœ¸ '

[julia]
symbol = 'î˜¤ '

[kotlin]
symbol = 'î˜´ '

[kubernetes]
symbol = 'ó±ƒ¾ '

[lua]
symbol = 'î˜  '

[nim]
symbol = 'î™· '

[nix_shell]
symbol = 'ó±„… '

[nodejs]
symbol = 'ó°™ '

[ocaml]
symbol = 'î™º '

[os.symbols]
Alpine = 'ïŒ€ '
Amazon = 'ï‰° '
Android = 'ó°€² '
Arch = 'ó°£‡ '
Artix = 'ïŒŸ '
CentOS = 'ïŒ„ '
Debian = 'ïŒ† '
EndeavourOS = 'ïŒ¢ '
Fedora = 'ïŒŠ '
FreeBSD = 'ïŒŒ '
Garuda = 'ïŒ· '
Gentoo = 'ó°£¨ '
Illumos = 'ïŒ¦ '
Linux = 'ó°Œ½ '
Macos = 'îœ‘ '
Manjaro = 'ïŒ’ '
Mint = 'ó°£­ '
NetBSD = "ğŸš© "
NixOS = "ïŒ“ "
OpenBSD = 'ïŒ¨ '
openSUSE = 'ïŒ” '
Pop = 'ïŒª '
Redhat = 'ó±„› '
RedHatEnterprise = 'ó±„› '
Solus = 'ïŒ­ '
Ubuntu = 'îœº '
Windows = 'î˜ª '

[perl]
symbol = 'î™¾ '

[php]
symbol = 'îœ½ '

[purescript]
symbol = 'î˜° '

[python]
symbol = 'î˜† '

[rlang]
symbol = 'îšŠ '

[ruby]
symbol = 'î˜… '

[rust]
symbol = 'îš‹ '

[scala]
symbol = 'îš '

[swift]
symbol = 'îš™ '

[terraform]
format = 'via [$symbol$version]($style) '
symbol = 'îšš '
detect_extensions = ['tf', 'tfplan', 'tfstate', 'tfvars']
detect_files = ['terragrunt.hcl']

[vlang]
symbol = 'îš¬ '

[zig]
symbol = 'îš© '
