# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: First interaction
on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.event.issue.number || github.event.pull_request.number }}
jobs:
  welcome:
    name: Welcome first-time contributors
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Greet first-time contributors
        uses: actions/first-interaction@v3
        with:
          repo_token: ${{ github.token }}
          issue_message: |
            Thanks for opening your first issue! We appreciate you taking the
            time to report this.

            Please make sure you've provided all the necessary details to help
            us understand and address your concern.
          pr_message: |
            Thanks for opening your first pull request! We appreciate your
            contribution.

            Please make sure your changes follow our contribution guidelines
            and include any necessary tests or documentation updates.
